# TensorFlowの各種オペレーション

このノートブックでは、TensorFlowの基本的なオペレーションを紹介します。

## 事前準備

In [2]:
import tensorflow as tf

sess = tf.Session()

#### tf.constant

In [40]:
constant_op = tf.constant(1)

print(constant_op)

print(sess.run(constant_op))

Tensor("Const_56:0", shape=(), dtype=int32)
1


## <a href="https://www.tensorflow.org/api_guides/python/math_ops#Arithmetic_Operators">Arithmetic Operators</a>

#### tf.add (加算)

In [6]:
sess.run(tf.add(tf.constant(1), tf.constant(2)))

3

#### tf.subtract

In [7]:
sess.run(tf.subtract(tf.constant(4), tf.constant(1)))

4

#### tf.multiply (乗算)

In [8]:
sess.run(tf.multiply(tf.constant(3), tf.constant(2)))

6

#### tf.scalar_mul (スカラー積)

In [13]:
sess.run(tf.scalar_mul(tf.constant(3), tf.constant(2)))

6

#### tf.div (除算)

In [17]:
sess.run(tf.div(tf.constant(3), tf.constant(2)))

1

#### tf.divide (除算)

In [16]:
sess.run(tf.divide(tf.constant(3), tf.constant(2)))

1.5

#### tf.truediv

In [19]:
sess.run(tf.truediv(tf.constant(4), tf.constant(2)))

2.0

#### tf.floordiv

In [20]:
sess.run(tf.floordiv(tf.constant(4), tf.constant(2)))

2

#### tf.realdiv

In [24]:
sess.run(tf.realdiv(tf.constant(3), tf.constant(2)))

InvalidArgumentError: No OpKernel was registered to support Op 'RealDiv' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]

	 [[Node: RealDiv_3 = RealDiv[T=DT_INT32](RealDiv_3/x, RealDiv_3/y)]]

Caused by op 'RealDiv_3', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 281, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 232, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 397, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2856, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-965520de38cc>", line 1, in <module>
    sess.run(tf.realdiv(3, 2))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 3342, in _real_div
    "RealDiv", x=x, y=y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'RealDiv' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]

	 [[Node: RealDiv_3 = RealDiv[T=DT_INT32](RealDiv_3/x, RealDiv_3/y)]]


#### tf.truncatediv

In [25]:
sess.run(tf.truncatediv(tf.constant(3), tf.constant(2)))

1

#### tf.floor_div

In [26]:
sess.run(tf.floor_div(tf.constant(3), tf.constant(2)))

1

#### tf.truncatemod

In [27]:
sess.run(tf.truncatemod(tf.constant(3), tf.constant(2)))

1

#### tf.floormod

In [28]:
sess.run(tf.floormod(tf.constant(3), tf.constant(2)))

1

#### tf.cross

In [32]:
sess.run(tf.cross(tf.constant([1, 2, 3]), tf.constant([4, 5, 6])))

array([-3,  6, -3], dtype=int32)

## <a href="https://www.tensorflow.org/api_guides/python/constant_op">Constants, Sequences, and Random Values</a>

### Constant Value Tensors

#### tf.zeros

In [4]:
sess.run(tf.zeros([2, 3], tf.int32))

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

#### tf.zeros_like

In [33]:
sess.run(tf.zeros_like(tf.constant([[1, 2, 3], [4, 5, 6]])))

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

#### tf.ones

In [35]:
sess.run(tf.ones([2, 3], tf.int32))

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

#### tf.ones_like

In [36]:
sess.run(tf.ones_like(tf.constant([[1, 2, 3], [4, 5, 6]])))

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

#### tf.fill

In [37]:
sess.run(tf.fill([2, 3], 9))

array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)

#### tf.constant

NOTE: 一番上で説明をしています

### Sequences

#### tf.lin_space

In [43]:
sess.run(tf.linspace(8.0, 12.0, 3))

array([ 8., 10., 12.], dtype=float32)

#### tf.range

### truncated_normal

In [6]:
x = tf.truncated_normal(shape=[10],mean=0.0, stddev=1.0,dtype=tf.float32)

with tf.Session() as sess:
    print(x.eval())

[ 0.03122769  0.6151206  -0.06283391 -0.1067424   0.05154543  1.1128749
  0.40602988 -0.42614138  1.1898931   1.106429  ]
